#!/usr/bin/env bash
#subdomain info

if [ "$#" -eq 1 ];then
	s=("www" "lb-01" "web-01" "web-02")
else
	s=$2
fi
for sd in "${s[@]}"
do
	dig "$sd.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{ print "The subdomain '$sd' is a " $4 " record and points to " $5}'
done
