#!/usr/bin/env bash
#sites enabled to sites abalaivle linking

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
