#!/usr/bin/env bash
# iterates from 1 to 10 and displays
#+ "bad luck" for the 4 iteration
#+ "good luck" for the 8 ITEration
#+ "Holberton School" instead

COUNTER=1
while [ $COUNTER -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done
