#!/usr/bin/env bash
#Script to run the nginx in respective user

pkill -f apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
